### PR TITLE
Added more savepoints and original map icons to LC & VC + buyable properties

### PR DESCRIPTION
**Pull request by HeicoDev**
## I have found some bugs... One bug is gamebreaking, so if I can't find a fix for it in the next days, I will close the pull request. So don't review/merge it now. I will update this post if anything changes. 
I have found a workaround for the minor problems, but I can't fix the gamebreaking bug.
After loading a save the map icon and the red sphere for avaible missions just disappear. 
It's a problem of fastmans limit adjuster or I just did something wrong. I don't know. 

**Preview Pictures**
previewlc
screenshot 45

**For more information see the commits below.**

Edit: Made all savepoints/properties buyable. (except for the starter savehouse in VC & LC)

**Alternative manual update** 
I haven't tested the update method with Git, because I prefer the manual way, but feel free to test it and report me here if a problem occurs.

1. Delete VCSaves.cs & LCSaves.cs inside the CLEO folder** of you GTA installation. 
2. Download my master branch. 
3. Copy the folder "VCLCSaves"* and the file "LCxVCIcons.cs"* to your 
    CLEO folder**.
4. Copy fastman92limitAdjuster_GTASA.ini*** to your GTA root folder.
5. Copy gtasa_radarBlipSpriteFilenames.dat**** to GTA SA\data
6. Copy hud.txd***** to GTA SA\modloader\SAxVCxLC\models or GTA SA\models
7. Enjoy!
 
*SAxVCxLC_source\extras\CLEO\...
**GTA San Andreas\CLEO\...
   or
   GTA San Andreas\modloader\SAxVCxLC\CLEO\...
***SAxVCxLC_source\base_root\...
****SAxVCxLC_source\base_root\data\...
*****SAxVCxLC_source\base\models\...

Edit 2: 
**Added original map icons to VC & LC.**
There are still some placeholders, but now it feels complete.
The radar blips are from GTA III, VC & LCS. (Mobile Versions)
_All the textures are extracted & converted by me!_

**Added LCS Safehouses to Liberty City.**
Added Liberty City Stories Safehouses to LC to match the amount of safehouses in VC better.
Except for the LCS safehouse in Portland, because the house is just a ruin on the GTA III map. 
_I haven't added any interiors!_ 
I have only placed a map icon, property pickup, save pickup & money pickup at the more or less right place.
I will update the scripts if anything get changed at the interiors.

**Known issues**
The new map icons are invisible on the map legend, but they using space.
So the map legend looks a bit messed up.
I think it's a problem of the Limit Adjuster, hopefully fastman will fix it in the future.
And/or he should add a feature to give the map icons a name for the legend. 

The icons are not 100% accurate on the main map, but this seems to be a problem of SAxVCxLC or GTA itself. On the mini map is everything accurate.

### CODE REVIEW

**Comment by inanahammad** [comment]
Is this fully complete?

**Comment by inanahammad** [comment]
I noticed you deleted some files

**Comment by HeicoDev** [comment]
Yes, it's fully complete and functional. The installation batch is also working.
I will also update the placeholder icons with more accurate ones in the future.
Download my master branch and test it yourself if you want. Bug reporting is also welcome.
All the files I deleted were added again later with another name in another folder. (CLEO\VCLCSaves\...)

Example: I changed the name of VCSaves.cs to VCHotel.cs and moved it to the location: SAxVCxLC_source\extras\CLEO\VCLCSaves\CLEO\ 
So after installation it is the location:
GTA San Andreas\CLEO\VCLCSaves\CLEO\
or
GTA San Andreas\modloader\SAxVCxLC\CLEO\VCLCSaves\CLEO\

The scripts in CLEO\VCLCSaves\CLEO\ are for the savepoints, the buyable properties and the map icons of a specific porperty. (map icon changes from "buyable property" to "Safehouse" after buying a house)
The other map icons are still in CLEO\LCxVCIcons.cs.

**Alternative manual update** 
if you don't want to install my master, because you want to backup your files first or just because the manual installation is easy and fast. :P Ah, and I haven't tested the update method with Git, because I prefer the manual way, but feel free to test it and report me here if a problem occurs.

1. Delete VCSaves.cs & LCSaves.cs inside the CLEO folder** of you GTA installation. 
2. Download my master branch and copy the folder "VCLCSaves"* and the file "LCxVCIcons.cs"* to your 
    CLEO folder**.
3. Enjoy!
 
*SAxVCxLC_source\extras\CLEO\...
**GTA San Andreas\CLEO\...
   or
   GTA San Andreas\modloader\SAxVCxLC\CLEO\...

**Comment by inanahammad** [comment]
Bro fully complete 100% and let me know ok.And make all the adjustments.I don't got access to my pc right now.Or else I could have helped you

**Comment by inanahammad** [comment]
and can you combine the Cleo's in a one Cleo.Cause multiple Cleo's will make the Cleo's folder a little messy with the other cleos

**Comment by inanahammad** [comment]
anyways checked your file sources and looks good to me.When good idea become active he would think about it ok

**Comment by HeicoDev** [comment]
Yeah, as I said already, it's fully complete and all adjustments are done! (It's the final version on the pics)
So everything will work "out of the box" after installing. 
No, sorry. I can't combine them... I don't know why, tried already different ways.
But I have sorted all savepoint scripts in one subfolder (CLEO\VCLCSaves\CLEO) to avoid the problem/mess you are talking about.
And thank you for liking my work! :)

**Comment by HeicoDev** [comment]
I tried the last days to fix the problem, but I failed... So I will close this pull request now.
I will open a new pull request if anything changes.

**Pull request closed without merging**
